In [1]:
import numpy as np
from hamiltonian import hamiltonian
from super_cell import super_cell
from k_space import k_space
from observables import observables
from slab import slab

# Import primitive bulk Hamiltonian

In [2]:
bra_vec   = np.array([[ 3.0730000,    0.0000000,    0.0000000],
                      [-1.5365000,    2.6612960,    0.0000000],
                      [ 0.0000000,    0.0000000,   20.0000000]])
spin      = True
basis     = np.array([0,1])
n_elec    = 4
inputfile = "../../test_ham/In_SiC_soc.dat"
Ham_bulk = hamiltonian(inputfile,bra_vec,spin,basis,N_ELEC=n_elec)

Reading Hamiltonian...
Time for reading hr-file:  0.0825958251953125
Hamiltonian from file ../../test_ham/In_SiC_soc.dat successfully loaded.
H(R) is spin-full and contains 149 R-vectors and 4 orbitals.


# Create super-cell

In [3]:
sup_vec = np.array([[ 1, 0, 0],
                    [ 1, 2, 0],
                    [ 0, 0, 1]])
Ham_super_cell = super_cell(Ham_bulk,sup_vec)

n_orb 8


# Test k-path

In [4]:
ktype     = "path"
kbasis    = "car"
vecs1      = np.array([[ 0, 0, 0],
                      [ 2, 0, 0],
                      [ 3, 3, 0]])
vecs2      = np.array([[ -2, 0, 0],
                      [  2, 0, 0]])

vecs      = np.array([[ -2,-2, 0],
                      [  2, 2, 0]])

npoints   = 100

K_space_prim = k_space(ktype,kbasis,vecs,Ham_bulk.bra_vec,npoints)
K_space_sup  = k_space(ktype,kbasis,vecs,Ham_super_cell.bra_vec,npoints)

# Test band structure

In [5]:
# Initializing observables
op_types = ["S","L"]
Observables_prim = observables(Ham_bulk,K_space_prim,op_types,PREFIX="prim_")
Observables_prim.calculate_ops()
Observables_prim = observables(Ham_super_cell,K_space_sup,op_types,PREFIX="sup_")
Observables_prim.calculate_ops()

Initializing k-independent operator S.
Initializing k-independent operator L.
Calculating operators on the given k-space...
Diagonalizing all k-points in parallel.
Time for running H(k) FT: 0.0022699832916259766
Time for diagonalizing H(k): 0.002176046371459961
Time for calculating expectation value of operator S: 0.0010190010070800781
Time for calculating expectation value of operator L: 0.0016391277313232422
Running post-processing for operator S.
Running post-processing for operator L.
Writing eigenvalues output.
Writing output for operator S.
Writing output for operator L.
Initializing k-independent operator S.
Initializing k-independent operator L.
Calculating operators on the given k-space...
Diagonalizing all k-points in parallel.
Hamiltonian is hermitian?: True
Time for running H(k) FT: 0.005583047866821289
Time for diagonalizing H(k): 0.00787496566772461
Time for calculating expectation value of operator S: 0.0019669532775878906
Time for calculating expectation value of operat

# Slab calculation, PBC along $x$

In [6]:
N_slab = 15
sup_vec = np.array([[ 1, 0, 0],
                    [ 1, 2, 0],
                    [ 0, 0, 1]])
sup_vec[1] *= N_slab
Ham_slab_x = super_cell(Ham_bulk,sup_vec,1)

n_orb 120


In [7]:
ktype     = "path"
kbasis    = "car"
vecs      = np.array([[ -2, 0, 0],
                      [  2, 0, 0]])

npoints   = 500

K_space_slab_x      = k_space(ktype,kbasis,vecs,Ham_slab_x.bra_vec,npoints)
K_space_slab_x_prim = k_space(ktype,kbasis,vecs,Ham_bulk.bra_vec,npoints)
K_space_slab_x_sup  = k_space(ktype,kbasis,vecs,Ham_super_cell.bra_vec,npoints)

In [8]:
op_types = ["S","L"]
Observables_slab_x = observables(Ham_slab_x,K_space_slab_x,op_types,PREFIX="slab_x_")
Observables_slab_x.calculate_ops()
Observables_slab_prim = observables(Ham_bulk,K_space_slab_x_prim,op_types,PREFIX="slab_prim_")
Observables_slab_prim.calculate_ops()
Observables_slab_sup = observables(Ham_super_cell,K_space_slab_x_sup,op_types,PREFIX="slab_sup_")
Observables_slab_sup.calculate_ops()

Initializing k-independent operator S.
Initializing k-independent operator L.
Calculating operators on the given k-space...
Diagonalizing all k-points in parallel.
Hamiltonian is hermitian?: True
Time for running H(k) FT: 2.20963716506958
Time for diagonalizing H(k): 6.4266111850738525
Time for calculating expectation value of operator S: 4.208778142929077
Time for calculating expectation value of operator L: 4.058600902557373
Running post-processing for operator S.
Running post-processing for operator L.
Writing eigenvalues output.
Writing output for operator S.
Writing output for operator L.
Initializing k-independent operator S.
Initializing k-independent operator L.
Calculating operators on the given k-space...
Diagonalizing all k-points in parallel.
Time for running H(k) FT: 0.0038590431213378906
Time for diagonalizing H(k): 0.007467031478881836
Time for calculating expectation value of operator S: 0.003966093063354492
Time for calculating expectation value of operator L: 0.004214

In [9]:
a=-3
diag = np.diag([1,1,1,0])
mat=np.roll(diag,5,axis=1)
#mat[:,:a]=0
mat

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [10]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
np.floor(3.5)

3.0

In [12]:
int(np.floor(-0.5))

-1

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])